
# 公開するページのURL
baseURL = "https://sheepla.github.io/sheepla-note"

languageCode = "ja"
DefaultContentLanguage = "ja"
HasCJKLanguage = true
enableRobotsTXT = true
paginate = 20

# ブログのタイトル
title = "sheepla-note"

# テーマ
theme = "mainroad"

# 自己紹介
[Author]
    name = "sheepla"
    bio = "Linux, Vim, PowerShell等を気ままに触っているただのひつじ。シンプルなソフトウェアが好きです。"
    avatar = "img/avatar.png"

[Params]
    subtitle = "ひつじのノート"
    description = "自分用の備忘録を兼ねて書いています。"
    authorbox = true
    copyright = "Sheepla"
    customCSS = ["css/custom.css"]
    post_meta = ["date", "categories"]
    readmore = true
    twitter_cards = true

# ページのテーマカラー
[Params.style.vars]
  highlightColor = "#444b71"

# サイドバー
[Params.sidebar]
    home = "right"
    list = "right"
    single = "right"
    widgets = ["search", "recent", "categories", "taglist", "social"]

# ウィジェット
[Params.widgets]
  tags_counter = true

# SNS等のユーザー名
[Params.widgets.social]
  twitter = "sheeeeepla"
  github = "sheepla"

