# 公開するページのURL
baseURL = "https://sheepla.github.io/sheepla-note"

languageCode = "ja"
DefaultContentLanguage = "ja"
HasCJKLanguage = true
enableRobotsTXT = true

# ブログのタイトル
title = "sheepla-note"

theme = "mainroad"
paginate = 20

# 自己紹介
[Author]
    name = "sheepla"
    bio = "Linux, Vim, PowerShell等を気ままに触っているただのひつじ。シンプルなソフトウェアが好きです。"
    avatar = "img/avatar.png"

[Params]
    customCSS = ["css/custom.css"]
    copyright = "Author"
    readmore = true
    authorbox = true
    post_meta = ["date", "categories"]
    twitter_cards = true

# ページのテーマカラー
[Params.style.vars]
  highlightColor = "#444b71"

# SNS等のユーザー名
[Params.widgets.social]
  twitter = "sheeeeepla"
  github = "sheepla"

[Params.sidebar]
    home = "right"
    list = "right"
    single = "right"
    widgets = ["search", "recent", "categories", "taglist", "social"]

